name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js & cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      # Ensure pnpm is available:
      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Fallback in case Corepack didn’t put pnpm on PATH:
      - name: Install pnpm globally
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test -- --passWithNoTests
