name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20 & cache deps
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install pnpm CLI
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run tests (allow no tests)
        run: pnpm run test -- --passWithNoTests

